### ISSUE TITLE
Issue with `HtmxAntiforgeryScript` and `hx-boost`

### ISSUE THREAD

**Issue by juchom** [khalidabuhakmeh/Htmx.Net#11]
I've spotted a potential issue with `HtmxAntiforgeryScript` when `hx-boost` is set to true.

If you modify you HTMX ToDo  `<body>` tag to

```html
<body hx-boost="true">
```

You start the application on first load, you open de dev console and type the following command : 

```
getEventListeners(window.document)
```

You'll have 1 handler on `htmx:configRequest`

![image](https://user-images.githubusercontent.com/17902415/197539309-1eddfbcc-a643-4fc2-9bfa-aea07dcb4067.png)

Now click several times on the menu and type the same command in the dev console

The handlers are stacking on the event

![image](https://user-images.githubusercontent.com/17902415/197539683-d98dbb43-e1f8-4580-9b28-eceacee23949.png)

Is this an issue or is it ok to have the handlers stacking ? (other events are also stacking)

**Comment by khalidabuhakmeh** [comment]
It shouldn't be a big deal, but I wonder if I could update the JavaScript code to check first before registering the event listener. Want to give it a try?

**Comment by khalidabuhakmeh** [comment]
@juchom your other option is to include the anti-forgery script in the `<head>` tag of the page. It will keep it from executing multiple times.

**Comment by khalidabuhakmeh** [comment]
I just released a new version `1.0.1`. I tested it locally and seems to work for me. Could you test please :)

**Comment by juchom** [comment]
Hi @khalidabuhakmeh,

Sorry for the late reply, I was very busy, I just tested and it works well 👍 

Thanks
