### ISSUE TITLE
Token in meta is not refreshed whith `hx-boost`

### ISSUE THREAD

**Issue by juchom** [khalidabuhakmeh/Htmx.Net#15]
Hello @khalidabuhakmeh,

Like in #11, the meta tag helper is not refreshing the token when used with boost.

Do you have any advice on how to solve this when boosting is enabled ?

**Comment by khalidabuhakmeh** [comment]
Boost only replaces the `body` tag, so you won't get a newly updated `meta` tag in the `head`.

You could try adding an additional `out of band` swap that could replace the meta tag on each boosted request.

There should be an `HX-BOOSTED` header to determine if a request is boosted or not and then apply the out-of-band element.

**Comment by khalidabuhakmeh** [comment]
@juchom I tried to do an out-of-band swap but realized boosts can't target anything but the `body` tag. So I wrote some JavaScript you can find in #16. You can try adding it to your apps to see if it helps. Your feedback is appreciated.

**Comment by khalidabuhakmeh** [comment]
Closing this issue since it was included with 1.1.0 release.
