### ISSUE TITLE
Dynamically update hx-post

### ISSUE THREAD

**Issue by dotnetshadow** [khalidabuhakmeh/Htmx.Net#18]
Hi there,

Just wondering if there any way to dynamically change the hx-post? I did change it in javascript using `setAttribute` but even though the url updates it keeps executing the original url?

Similar to this
https://github.com/bigskysoftware/htmx/issues/882

Any ideas would be appreciated

**Comment by khalidabuhakmeh** [comment]
Why would you want to change the `hx-post` dynamically? I'm trying to understand your use case.

**Comment by khalidabuhakmeh** [comment]
Add an event handler for `htmx:configRequest` and modify the path. If you're using the script that comes with this package you may want to paste it in your project and add the changes there.

```
<script>
window.addEventListener("htmx:configRequest", (evt) => {
    console.log(evt.detail);   
    if (evt.detail.verb == "get") {
        evt.detail.path = "/?handler=Snippet";
    }
});
</script>
```

**Comment by dotnetshadow** [comment]
> Why would you want to change the `hx-post` dynamically? I'm trying to understand your use case.

I was trying to pass in an id to the post dynamically. In my case I have say tabs that get dynamically generated and I wanted to update the id for the post. I sort of figured another way around it by reloading the entire tabs once one is added etc
