### ISSUE TITLE
Htmx.Net doesn't work in a cross origin context without a CORS policy

### ISSUE THREAD

**Issue by tanczosm** [khalidabuhakmeh/Htmx.Net#33]
When using htmx in a cross origin context, the server must set Access-Control headers in order for htmx headers to be visible on the client side.  See [https://htmx.org/docs/#cors](https://htmx.org/docs/#cors)

Specifically the server end would need to set the response header "[Access-Control-Expose-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers)" to a comma-delimited list of all of the headers that are used and should be made available to scripts running in the browser.  

Asp.net can do this with a Cors policy pretty easily.

I don't have a PR for this but I'm trying to get your opinion if something like this could be included under the veil of Htmx.Net.

Cors policy building could be made available via an extensions method (HtmxCorsPolicyBuilderExtensions.cs?) that extends the [CorsPolicyBuilder](https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/CORS/src/Infrastructure/CorsPolicyBuilder.cs)?

Effectively add a method kind of like this (this is coded in browser so I'm spitballing):
```csharp
    /// <summary>
    /// Adds Htmx request headers to the policy.
    /// </summary>
    /// <returns>The current policy builder.</returns>
    public static CorsPolicyBuilder WithHtmxHeaders(this CorsPolicyBuilder policyBuilder)
    {
        policyBuilder.WithHeaders( ... string array of htmx request headers ...);

        return policyBuilder;
    }
```

```csharp
    /// <summary>
    /// Adds Htmx response headers to the policy.
    /// </summary>
    /// <returns>The current policy builder.</returns>
    public static CorsPolicyBuilder WithExposedHtmxHeaders(this CorsPolicyBuilder policyBuilder)
    {
        policyBuilder.WithExposedHeaders( ... string array of htmx response headers ...);

        return policyBuilder;
    }
```

Then build your policy with something like:
```csharp
var  MyAllowSpecificOrigins = "_myAllowSpecificOrigins";

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddCors(options =>
{
    options.AddPolicy(name: MyAllowSpecificOrigins,
                      policy  =>
                      {
                          policy.WithOrigins("http://example.com", "http://www.contoso.com")
                                   .WithHtmxHeaders()  // Add request headers
                                   .WithExposedHtmxHeaders()  // Add response headers
                      });
});
```

Thoughts?

**Comment by khalidabuhakmeh** [comment]
CORS is really specific to each application and wether the developer is choosing to do so. I am not sure any mention of CORS should be in the library, but an update to the Readme.md about techniques to address CORS would be appreciated.

**Comment by tanczosm** [comment]
See #34
