### ISSUE TITLE
Antiforgery header is not sent with hx-delete

### ISSUE THREAD

**Issue by woodian** [khalidabuhakmeh/Htmx.Net#37]
Hi,

Your antiforgery snippet has an issue with the shortcut path when the page contains an unrelated form.

In my case the page contains both a form to update an entity and a list of other (sub-)entities for which I want to be able to delete each of those. When the hx-delete is requested, the snippet is triggered but it verifies that there is an antiforgery hidden field in the form and thus doesn't add the required header.

I worked around this by changing the problematic line to
`if (httpVerb === 'POST' && evt.detail.parameters[antiForgery.formFieldName])`

This fixes my immediate problem but seems to be too simplistic and most probably doesn't handle all the cases.

**Comment by khalidabuhakmeh** [comment]
Could you provide me with the Razor/HTML of a page with your example?

**Comment by khalidabuhakmeh** [comment]
If I had to guess from your explanation, you have "overlapping forms". The `hx-delete` attribute should invoke an endpoint with the `DELETE` HTTP method. 

A reproduction would be helpful thought :)

**Comment by woodian** [comment]
There is only one form in the page.
Here is the Razor generated page (I removed the header and footer for brevity):

`<div>
    <hr />
    <form method="post">
        
        <input type="hidden" data-val="true" data-val-required="The Id field is required." id="Venue_Id" name="Venue.Id" value="4883d3ee-5b6f-4cc2-9d1f-6d8ea2fc29ff" />
        <input type="hidden" data-val="true" data-val-required="The TenantId field is required." id="Venue_TenantId" name="Venue.TenantId" value="90bfd872-0ed5-4edb-a12b-a23c4cab390c" />
        <dl class="row">
            <dt class="col-sm-2">
                Name
            </dt>
            <dd class="col-sm-10">
                <input class="form-control" type="text" data-val="true" data-val-length="The field Name must be a string with a maximum length of 100." data-val-length-max="100" data-val-required="The Name field is required." id="Venue_Name" maxlength="100" name="Venue.Name" value="v2" />
                <span class="text-danger field-validation-valid" data-valmsg-for="Venue.Name" data-valmsg-replace="true"></span>
            </dd>
            <dt class="col-sm-2">
                Address
            </dt>
            <dd class="col-sm-10">
                <input class="form-control" type="text" data-val="true" data-val-length="The field Address must be a string with a maximum length of 255." data-val-length-max="255" data-val-required="The Address field is required." id="Venue_Address" maxlength="255" name="Venue.Address" value="my street 3" />
                <span class="text-danger field-validation-valid" data-valmsg-for="Venue.Address" data-valmsg-replace="true"></span>
            </dd>
            <dt class="col-sm-2">
                LandingPage
            </dt>
            <dd class="col-sm-10">
                <input class="form-control" type="text" data-val="true" data-val-length="The field LandingPage must be a string with a maximum length of 1000." data-val-length-max="1000" data-val-required="The LandingPage field is required." id="Venue_LandingPage" maxlength="1000" name="Venue.LandingPage" value="https://morfus.ai/" />
                <span class="text-danger field-validation-valid" data-valmsg-for="Venue.LandingPage" data-valmsg-replace="true"></span>
            </dd>
            <dt class="col-sm-2">
                Language
            </dt>
            <dd class="col-sm-10">
                <input class="form-control" type="text" data-val="true" data-val-length="The field Language must be a string with a maximum length of 7." data-val-length-max="7" data-val-required="The Language field is required." id="Venue_Language" maxlength="7" name="Venue.Language" value="en" />
                <span class="text-danger field-validation-valid" data-valmsg-for="Venue.Language" data-valmsg-replace="true"></span>
            </dd>
        </dl>
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    <input name="__RequestVerificationToken" type="hidden" value="CfDJ8IgoOB59uk1MhyluGzed4Oc4OjQHPDOF2Di44MFx_U7VtQHswH4j483LdmZjHwRzcVzxbbdVrTrzbKQD2VlOfXX2POJLtH-lkNbG9kD5z4X6n0gFFaxlE8U-hRJDyna0vEbps1Cnv-vpDh7XuNfR-uo" /></form>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Templates
                    <a class="icon" href="/Templates/Create?v=4883d3ee-5b6f-4cc2-9d1f-6d8ea2fc29ff"><svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24"><path d="M440-280h80v-160h160v-80H520v-160h-80v160H280v80h160v160Zm40 200q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 83-31.5 156T763-197q-54 54-127 85.5T480-80Zm0-80q134 0 227-93t93-227q0-134-93-227t-227-93q-134 0-227 93t-93 227q0 134 93 227t227 93Zm0-320Z"/></svg></a>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody hx-confirm="Are you sure?" hx-target="closest tr" hx-swap="outerHTML swap:1s">
                <tr class="list-row">
                    <td>
                        <a class="d-flex w-100" href="/Templates/Edit?id=13">
                            t3
                        </a>
                    </td>
                    <td>
                        <a class="icon" hx-delete="/Templates?venue-id=4883d3ee-5b6f-4cc2-9d1f-6d8ea2fc29ff&amp;id=13"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
  <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0"/>
</svg>
</a>
                        <a target="_blank" href="/Portal/Welcome?venue-id=4883d3ee-5b6f-4cc2-9d1f-6d8ea2fc29ff&amp;id=13">Go to portal</a>
                    </td>
                </tr>
                <tr class="list-row">
                    <td>
                        <a class="d-flex w-100" href="/Templates/Edit?id=14">
                            template1
                        </a>
                    </td>
                    <td>
                        <a class="icon" hx-delete="/Templates?venue-id=4883d3ee-5b6f-4cc2-9d1f-6d8ea2fc29ff&amp;id=14"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
  <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0"/>
</svg>
</a>
                        <a target="_blank" href="/Portal/Welcome?venue-id=4883d3ee-5b6f-4cc2-9d1f-6d8ea2fc29ff&amp;id=14">Go to portal</a>
                    </td>
                </tr>
        </tbody>
    </table>
</div>`

The problematic hx-delete requests are in the table below the form.

**Comment by khalidabuhakmeh** [comment]
Let me try it out and see what I can find out. Please hold...

**Comment by khalidabuhakmeh** [comment]
Aaaaah. I think I see your issue. Your `hx-delete` is not within the scope of the original form so HTMX doesn't have an anti-forgery token when building the request (see screenshot below). You have a few options to fix this issue:

- Add a request forgery token header to each delete call as a header. Check out #36 for an example. 
- Use the `htmx-config` header to have the JavaScript do it for you
- Wrap the deletes within the original form and resubmit the entire form.
- Wrap each button with a form and put `hx-delete` on the form and have the button submit the form.

Personally, I like the third option because you have a chance to update the entire form along with the anti-forgery token on each request.

It's also important to remember that `hx-delete` relates to the HTTP method not the user's intention. This can be an issue in Razor Pages which only technically supports `GET` and `POST` methods. (I wrote about it here https://khalidabuhakmeh.com/more-http-methods-aspnet-core-html-forms)

Could you try some of the approaches outlined above and let me know which one you end up going with.

![JetBrains Rider-EAP -2023-10-18 -08-14-14](https://github.com/khalidabuhakmeh/Htmx.Net/assets/228256/4a68fd52-8ddf-4a4f-895d-e897c1e59af7)

**Comment by woodian** [comment]
Options 1 and 4 would work but are somewhat unwieldy.

Option 3 doesn't make much sense in my particular case because the form part is logically separated from the list part.

I'm not sure what you mean by option 2.

I used:
 `<meta name="htmx-config" historyCacheSize="20" indicatorClass="htmx-indicator" includeAspNetAntiforgeryToken="true" />`
in conjunction with:
`<script src="@HtmxAntiforgeryScriptEndpoints.Path" defer></script>`

I don't know if this is what you mean, but this is what I'm saying that is not working.

In regard to Razor Pages not supporting HTTP DELETE, I added a OnDeleteAsync() method on the respective .cshtml.cs file and it processes the requests. Whether that's undocumented or unintended behavior or some side effect, I don't know. But it sure works.

**Comment by ptfw** [comment]
in regard to Razor Pages support for other verbs such as DELETE, PUT, and PATCH, those verbs are supported (and I also use those successfully as well) ... according to the following documentation, they're converted to POST
https://github.com/timheuer/Docs-1/blob/master/aspnetcore/razor-pages/razor-pages-conventions.md

**Comment by khalidabuhakmeh** [comment]
@woodian With option 2, you should see a JSON object in the final rendered HTML for `htmx-config` with an anti-forgery token. You need to register the tag helper correctly in your ViewImports file. Please double-check that this element is being transformed.

@ptfw is correct, the `OnDeleteAsync` method just so happens to have the word `delete` in it, but that doesn't mean it is the HTTP Method of `DELETE`. HTML forms (and thus Razor pages) only support `POST` and `GET` methods, but HTMX's `hx-delete` invokes the `DELETE` method.

**Comment by khalidabuhakmeh** [comment]
@woodian I've confirmed that the JavaScript works. I created a sample on a [separate branch](https://github.com/khalidabuhakmeh/Htmx.Net/pull/new/delete-from-form) to show what you need to do to use `hx-delete`. Tbh, I'd use `hx-post` in the case of using Razor Pages. I'll describe the steps below.

1. Add the `UseHttpMethodOverride` middleware and give it a proper name. I just used `HttpMethod` to keep it simple.

```csharp
app.UseHttpMethodOverride(new HttpMethodOverrideOptions
{
    FormFieldName = nameof(HttpMethod) 
});
```

2. Add your Razor Pages endpoint, it can be called anything you like.

```
public IActionResult OnDelete()
{
    return Content("Deleted 💥");
}
```

3. Apply the correct HTMX attributes (I'm using the tag helpers of this library). Make sure to add the HTTP method override to the request using `hx-vals`.

```razor
<div class="container">
    <div class="col mt-3">
        <h2> List To Delete Things</h2>

        <ul>
            @for (var i = 0; i < 5; i++)
            {
                <li hx-delete
                    style="margin: 1em; border: 1px solid black"
                    hx-page="Forms"
                    hx-page-handler="Delete"
                    hx-vals='{ "@nameof(HttpMethod)" : "DELETE" }'>
                    Happy Item 😁
                </li>
            }

        </ul>
    </div>
</div>
```

4. See it in action.

![Arc -2023-10-19 -13-58-21](https://github.com/khalidabuhakmeh/Htmx.Net/assets/228256/64e3eb10-1cfe-4fb2-8ba7-531c9eace1cb)

5. Consider switching to `hx-post` to avoid these shenanigans.

**Comment by woodian** [comment]
You are focusing on the wrong part of the issue. The problem is not the `hx-delete`. I tried your sample and it worked. That made me go back to my own project and re-check everything. I think I now know what the problem is.

But first, you don't need to inject any middleware to make `hx-delete` work. On my tests with your sample I removed it plus the `hx-page-handler` and `hx-vals` attributes and it worked (because you named your handler `OnDelete`). So no extra hassle by using `hx-delete`.

Back to my problem. I think I was led astray by my own debugging. I copied your antiforgery snippet to the default `site.js` file and proceeded with the change I mentioned in the first post. And it worked, but not for the reason I thought.

So, after testing your sample, I reverted to using `<script src="@HtmxAntiforgeryScriptEndpoints.Path" defer></script>`.

So, now I'm back to my first problem. `hx-delete` request works on some pages but not on others. I looked at my server logs and found this:
* for pages that work: `Request finished HTTP/2 GET https://localhost:7123/_htmx/antiforgery.js - - - 200`
* for a page that doesn't work: `Request finished HTTP/2 GET https://localhost:7123/Venues/_htmx/antiforgery.js - - - 404`

Do note that the path changed. Also, the script is injected in the `_Layout.cshtml` that is shared by all pages.

I believe that the problem is in here (src/Htmx.TagHelpers/HtmxAntiforgeryScriptEndpoints.cs):
`public static string Path { get; private set; } = "_htmx/antiforgery.js";`

Most probably that shouldn't  be a relative path. Your sample works because all pages are on the same path.

BTW, in this last round of debugging I also tried to replace `hx-delete` with `hx-post` and got the same problem.

**Comment by khalidabuhakmeh** [comment]
@woodian You're right. That shouldn't be a relative path, it should be `/_htmx/antiforgery.js`. Doh! I'll get a fix in and deploy. I guess the workaround for now is you can set the Path to fix the issue.

Thanks for finding this. 🤦‍♂️

**Comment by woodian** [comment]
@khalidabuhakmeh thank you for this most useful library. I'm sorry that my initial report wasn't accurate.

**Comment by khalidabuhakmeh** [comment]
No worries. I'm glad you're finding it very useful, and this is the kind of stuff that's good to find out sooner than later. I'm just happy it was an easy fix. Cheers :)
