### ISSUE TITLE
Support for additional response-header "HX-Reselect"

### ISSUE THREAD

**Issue by mollsju** [khalidabuhakmeh/Htmx.Net#40]
There's no extension in `Response.Htmx()` to do a Reselect.

If you wish for me to add this let me know.

**Comment by khalidabuhakmeh** [comment]
Could you clarify what a `Reselect` is? I'm not entirely sure what that is.

**Comment by mollsju** [comment]
I see you merged already, but it basically tells the client to not replace with its initial select but instead use the given css-selector. 
Useful when you might want a form to always do select on itself to handle validation , but want to refresh a bigger portion / update another target of the page after a successful post.

Thanks for adding it in!
